/**
 * The keys page, built as an app of its own.
 *
 * `vite.config.ts` builds the bench — five pages that read the library, play
 * rendered MP3s and talk to dev-server APIs. None of that can leave this
 * machine: `public/audio/` is 40 MB of gitignored renders, and every write
 * button is a Vite plugin that exists only while `npm run dev` is running.
 *
 * The keys page is the one exception, and it is the exception because of what
 * it *is*: the only page here that synthesises. It needs no audio files, no
 * manifest, no compositions — a voice is a few numbers, the notes come out of
 * your hands, and the whole app is React, Tone and the `voices/` presets Vite
 * bundles into it. So it is the one page that can be put on the internet and
 * still be the same page.
 *
 * Three differences from the bench build, all of them forced:
 *
 * - **`base: "./"`.** The output has to work at `/`, at `/music-generator/`
 *   (GitHub Pages serves a project site from a subpath) and from a file. Every
 *   asset reference is relative, which is true of the service worker's scope
 *   too.
 * - **`publicDir: false`.** `public/` holds those 40 MB of renders. The three
 *   files this app actually wants out of it are copied by name below.
 * - **`keys.html` → `index.html`.** A host serves a directory, and the phone
 *   URL should be the bare domain rather than a domain with a filename on the
 *   end of it.
 *
 * See [`docs/deploy.md`](./docs/deploy.md) for what to do with `dist-keys/`.
 */
import { createHash } from "node:crypto";
import { copyFileSync, readdirSync, renameSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";

/** Where the built app lands. Gitignored, like `dist/`. */
const OUT_DIR = "dist-keys";

/**
 * Files copied out of `public/` by name.
 *
 * By name rather than by copying the folder because the folder is mostly
 * rendered audio the keys app has no use for — see `publicDir: false` above.
 */
const STATIC_FILES = [
  "keys.webmanifest",
  "keys-icon-180.png",
  "keys-icon-192.png",
  "keys-icon-512.png",
];

export default defineConfig({
  base: "./",
  publicDir: false,
  plugins: [react(), keysApp()],
  // This build is the one with a service worker on it — see `src/globals.d.ts`.
  define: { __KEYS_APP__: "true" },
  build: {
    outDir: OUT_DIR,
    emptyOutDir: true,
    rollupOptions: {
      input: { keys: resolve(__dirname, "keys.html") },
    },
  },
  resolve: {
    alias: {
      "@engine": resolve(__dirname, "src/engine"),
      "@utils": resolve(__dirname, "src/utils"),
      "@app": resolve(__dirname, "src/app"),
    },
  },
});

/**
 * Everything that makes the built page an *app* rather than a page: the entry
 * filename, the icons and manifest, and a service worker that lets it open with
 * no signal.
 *
 * It runs on `writeBundle` — after Vite has written the files — because the
 * service worker's job is to name every file that exists, and the cheapest way
 * to know that list is to read the directory that now holds them.
 */
function keysApp(): Plugin {
  return {
    name: "music-generator:keys-app",
    apply: "build",
    writeBundle(options) {
      const dir = resolve(options.dir ?? OUT_DIR);

      // A host serves `index.html` for a bare URL; Vite names the output after
      // the input, which is `keys.html`.
      renameSync(join(dir, "keys.html"), join(dir, "index.html"));

      for (const file of STATIC_FILES) {
        copyFileSync(resolve(__dirname, "public", file), join(dir, file));
      }

      const files = walk(dir, dir).sort();
      writeFileSync(join(dir, "sw.js"), serviceWorker(files), "utf8");
      console.log(`\n  keys app → ${OUT_DIR}/  (${files.length + 1} files, offline-capable)`);
    },
  };
}

/** Every file under `dir`, as paths relative to it with forward slashes. */
function walk(dir: string, root: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) return walk(path, root);
    return [relative(root, path).split("\\").join("/")];
  });
}

/**
 * A precaching service worker, written against the file list rather than
 * generated by a framework.
 *
 * It is this short because the app is static and its asset names carry content
 * hashes: anything that changed has a new name, so "cache first, forever" is
 * correct for everything except the entry document. That one is fetched from
 * the network first so a deploy is picked up on the next load with signal, and
 * falls back to the cache when there is none — which is the case this exists
 * for. A keyboard that needs a connection to make a sound is not an instrument.
 */
function serviceWorker(files: readonly string[]): string {
  // The version is the file list, so a build that changed nothing keeps its
  // cache and a build that changed anything gets a new one.
  const version = createHash("sha256").update(files.join("\n")).digest("hex").slice(0, 12);
  const precache = JSON.stringify(["./", ...files], null, 2);
  return `/* Generated by vite.keys.config.ts — do not edit. */
const CACHE = "keys-${version}";
const PRECACHE = ${precache};

/*
 * \`ignoreVary\` because a static host is entitled to send \`Vary: Accept-Encoding\`
 * on anything it compresses, and a cache match that honours it then misses on
 * the app's own JavaScript — the one file that must never be missed, since
 * missing it offline is a blank page. The URL is the whole identity here:
 * every asset name carries a content hash, and nothing is negotiated.
 */
const MATCH = { ignoreVary: true };

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;

  // The document: network first, so a deploy lands on the next load that has
  // signal, and cache second, so the app opens on a train.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match("./", MATCH).then((hit) => hit || caches.match("./index.html", MATCH)),
      ),
    );
    return;
  }

  // Everything else is content-hashed, so a hit is always the right bytes.
  event.respondWith(
    caches.match(request, MATCH).then((hit) => hit || fetch(request).then((response) => {
      if (response.ok) {
        const copy = response.clone();
        caches.open(CACHE).then((cache) => cache.put(request, copy));
      }
      return response;
    })),
  );
});
`;
}
